
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nadia putri
 */
public class Frame1 extends javax.swing.JFrame {
    String temp="";
    Double ti, bt, h1;

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        tfTinggi = new javax.swing.JTextField();
        tfBerat = new javax.swing.JTextField();
        rbPerempuan = new javax.swing.JRadioButton();
        rbLaki = new javax.swing.JRadioButton();
        btnHitung = new javax.swing.JButton();
        btnLagi = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfIdeal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfHasil = new javax.swing.JTextField();
        tfHasil2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 10, 220, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 110, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Tinggi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 110, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Berat Badan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 150, 110, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 190, 110, 15);

        tfNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaActionPerformed(evt);
            }
        });
        getContentPane().add(tfNama);
        tfNama.setBounds(150, 50, 170, 40);

        tfTinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTinggiActionPerformed(evt);
            }
        });
        getContentPane().add(tfTinggi);
        tfTinggi.setBounds(150, 90, 100, 40);
        getContentPane().add(tfBerat);
        tfBerat.setBounds(150, 130, 100, 40);

        buttonGroup1.add(rbPerempuan);
        rbPerempuan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbPerempuan.setText("Perempuan");
        rbPerempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPerempuanActionPerformed(evt);
            }
        });
        getContentPane().add(rbPerempuan);
        rbPerempuan.setBounds(140, 190, 120, 23);

        buttonGroup1.add(rbLaki);
        rbLaki.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbLaki.setText("Laki - Laki");
        rbLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLakiActionPerformed(evt);
            }
        });
        getContentPane().add(rbLaki);
        rbLaki.setBounds(260, 190, 140, 23);

        btnHitung.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        getContentPane().add(btnHitung);
        btnHitung.setBounds(70, 250, 80, 40);

        btnLagi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLagi.setText("Coba Lagi");
        btnLagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLagiActionPerformed(evt);
            }
        });
        getContentPane().add(btnLagi);
        btnLagi.setBounds(180, 250, 100, 40);

        btnKeluar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar);
        btnKeluar.setBounds(300, 250, 80, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Berat badan ideal anda adalah");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 330, 162, 15);
        getContentPane().add(tfIdeal);
        tfIdeal.setBounds(220, 310, 80, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("cm");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(260, 120, 70, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("kg");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(260, 154, 70, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("kg");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(310, 330, 13, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(160, 360, 200, 30);
        getContentPane().add(tfHasil);
        tfHasil.setBounds(30, 390, 390, 30);
        getContentPane().add(tfHasil2);
        tfHasil2.setBounds(30, 430, 390, 30);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 450, 470);

        setBounds(0, 0, 470, 512);
    }// </editor-fold>//GEN-END:initComponents

    private void tfTinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTinggiActionPerformed

    private void tfNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        if (tfNama.getText().equals("")||tfBerat.getText().equals("")
                ||tfTinggi.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Data masukan harus diisi");
        }else if(rbPerempuan.isSelected()||rbLaki.isSelected()){
            try{
                Proses();
            }catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Inputan salah");
            }
        }else {
            JOptionPane.showMessageDialog(null, "Radio Button harus dipilih");
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void rbPerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPerempuanActionPerformed
        rbPerempuan.setSelected(false);
    }//GEN-LAST:event_rbPerempuanActionPerformed

    private void rbLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLakiActionPerformed
        rbLaki.setSelected(false);
    }//GEN-LAST:event_rbLakiActionPerformed

    private void btnLagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLagiActionPerformed
        tfNama.setText("");
        tfTinggi.setText("");
        tfBerat.setText("");
        tfHasil.setText("");
        tfHasil2.setText("");
        tfIdeal.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_btnLagiActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnLagi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTextField tfBerat;
    private javax.swing.JTextField tfHasil;
    private javax.swing.JTextField tfHasil2;
    private javax.swing.JTextField tfIdeal;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfTinggi;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
    ti = Double.parseDouble(tfTinggi.getText());
    bt = Double.parseDouble(tfBerat.getText());
    
    if (rbPerempuan.isSelected()) {
        h1 = (ti - 100) * 1;
    } else if (rbLaki.isSelected()){
        h1 = (ti - 104) * 1;
    }
    temp = Double.toString(h1.intValue());
    
    if (h1 < bt) {
        tfIdeal.setText(temp);
        tfHasil.setText("Maaf " + tfNama.getText() + " , Sepertinya anda Overweight");
        tfHasil2.setText("Banyaklah berolahraga dan hindari makanan berkolesterol");
    } else if (h1 > bt) {
        tfIdeal.setText(temp);
        tfHasil.setText("Maaf " + tfNama.getText() + " , Sepertinya anda Underweight");
        tfHasil2.setText("Banyaklah mengonsumsi makanan yang berkarbohidrat");
    } else {
        tfIdeal.setText(temp);
        tfHasil.setText("Hello " + tfNama.getText() + " , Berat badan anda sudah ideal");
        tfHasil2.setText("Lanjutkan pola makan teratur dan gaya hidup sehat ");
    }
    }
}
